import type { AtlasDef } from "../atlasDefs";

export const ContactAtlas: AtlasDef = {
    compress: true,
    images: [
        "map/map-cannon-01.png",
        "map/map-loading-blast-01.png",
        "map/map-loading-blast-02.png",
        "map/map-loading-blast-03.png",
        "map/map-loading-blast-04.png",
        "map/map-loading-blast-05.png",
        "map/map-loading-blast-06.png",
        "map/map-loading-blast-07.png",
        "map/map-loading-blast-08.png",
        "map/map-loading-blast-09.png",
        "map/map-loading-blast-10.png",
        "map/map-loading-blast-11.png",
        "map/map-skitter-res.png",
        "map/map-spaceship-01.png",
        "map/map-spaceship-fusion-01.png",
        "map/map-spaceship-fusion-02.png",
        "map/map-spaceship-fusion-03.png",
        "map/map-spaceship-fusion-04.png",
        "map/map-target.png",
        "map/ping-map-motherShip.png",
        "map/slime.png",
        "map/skitter-walking-1.png",
        "map/skitter-walking-2.png",
        "map/skitter-walking-3.png",
        "map/skitter-walking-4.png",
        "particles/blood-particle-1.png",
        "particles/blood-particle-2.png",
        "particles/blood-particle-3.png",
        "particles/blood-particle-4.png",
        "particles/blood-particle-5.png",
        "particles/blood-particle-6.png",
        "particles/blood-skitter-particle-1.png",
        "particles/blood-skitter-particle-2.png",
        "particles/blood-skitter-particle-3.png",
        "particles/blood-skitter-particle-4.png",
        "particles/blood-skitter-particle-5.png",
        "particles/blood-skitter-particle-6.png",
        "particles/part-lightning-burst-01.png",
    ],
};
