import type { AtlasDef } from "../atlasDefs";
import { BuildingSprites } from "./buildings";

export const PerksAtlas: AtlasDef = {
    compress: true,
    images: [
        ...BuildingSprites.reactor,
        ...BuildingSprites.bunker_chrys,
        ...BuildingSprites.bunker_crossing,
        ...BuildingSprites.bunker_hydra,
        ...BuildingSprites.warehouse_complex,
        ...BuildingSprites.bunker_twins,
        ...BuildingSprites.saloon,
        ...BuildingSprites.greenhouse_aged,
        ...BuildingSprites.bunker_chrys_aged,
        "map/map-silo-09.svg",
        "map/map-gun-lasr.svg",
        "map/map-vat-eye.svg",
        "map/map-vat-h20.svg",
        "map/map-vat-space-snout.svg",
        "map/map-vat-cosmic-blue.svg",
        "map/map-vat-brain.svg",
        "map/map-vat-explosive.svg",
        "map/map-airdrop-01-perk.svg",
        "map/map-airdrop-02-perk.svg",
        "map/map-chute-01-perk.svg",
        "map/map-crate-11-perk.svg",
        "map/map-crate-10-perk.svg",
        "map/map-crate-02-perk.svg",
        "map/map-crate-01-perk.svg",
        "map/map-bush-01-perk.svg",
        "map/map-bush-07-perk.svg",
        "map/map-bush-res-perk.svg",
        "map/map-tree-01-perk.svg",
    ],
};
