export const loadoutGunSections = [
    {
        name: "Pistols",
        guns: [
            "m9",
            "m9_dual",
            "hud-m9_dual",
            "m93r",
            "m93r_dual",
            "hud_m93r_dual",
            "glock",
            "glock_dual",
            "hud_glock_dual",
            "p30l",
            "p30l_dual",
            "ot38",
            // "ot38_dual",
            // "ots38_dual",
            "ots38",
            "deagle",
            "deagle_dual",
            "colt45",
            "colt45_dual",
            "m1911",
            "m1911_dual",
            // "lasr_gun",
            // "lasr_gun_dual",
        ],
    },
    {
        name: "SMGs",
        guns: ["mp5", "mac10", "ump9", "vector", "vector45", "scorpion", "m1a1"],
    },
    {
        name: "Shotguns",
        guns: [
            "m870",
            "m1100",
            // "m1014",
            "mp220",
            // "saiga",
            "spas12",
        ],
    },
    {
        name: "Snipers",
        guns: [
            "mosin",
            // "sv98",
            // "awc",
            // "garand",
            "scout_elite",
            "model94",
            "blr",
        ],
    },
    {
        name: "DMRs",
        guns: ["m39", "svd", "vss", "mk12", "l86"],
    },
    {
        name: "Rifles",
        guns: [
            "scar",
            "an94",
            "groza",
            "grozas",
            "famas",
            "hk416",
            "m4a1",
            // "scarssr",
        ],
    },
    {
        name: "LMGs",
        guns: ["dp28", "qbb97", "bar"],
    },
    {
        name: "Other",
        guns: [
            // "bugle",
            // "m9A17",
            // "m79",
            // "waterGun",
            // "rainbow_blaster",
            // "bazooka",
            "flux_rifle",
            "snow_cannon",
        ],
    },
] as const;

export const allowedGuns = [
    ...new Set(loadoutGunSections.flatMap((section) => section.guns)),
];
