import { Rarity } from "../../gameConfig";

export enum EmoteCategory {
    Locked,
    Faces,
    Food,
    Animals,
    Logos,
    Other,
    Flags,
    Default,
}

export interface EmoteDef {
    readonly type: "emote";
    name?: string;
    rarity?: Rarity;
    texture: string;
    sound: string;
    channel: string;
    teamOnly?: boolean;
    category: number;
    noCustom?: boolean;
    // Animated emote properties (from surviv.io)
    isAnimated?: boolean;
    animationSpeed?: number;
    animationScale?: number;
    sprites?: string[];
}

export const EmotesDefs: Record<string, EmoteDef> = {
    emote_medical: {
        type: "emote",
        texture: "emote-medical-healthkit.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_ammo: {
        type: "emote",
        texture: "ammo-box.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_ammo9mm: {
        type: "emote",
        texture: "ammo-9mm.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_ammo12gauge: {
        type: "emote",
        texture: "ammo-12gauge.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_ammo762mm: {
        type: "emote",
        texture: "ammo-762mm.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_ammo556mm: {
        type: "emote",
        texture: "ammo-556mm.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_ammo50ae: {
        type: "emote",
        texture: "ammo-50AE.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_ammo308sub: {
        type: "emote",
        texture: "ammo-308sub.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_ammoflare: {
        type: "emote",
        texture: "ammo-flare.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_ammo45acp: {
        type: "emote",
        texture: "ammo-45acp.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: true,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_loot: {
        type: "emote",
        texture: "",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_trick_nothing: {
        type: "emote",
        texture: "face-imp-trick.img",
        sound: "trick_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_trick_size: {
        type: "emote",
        texture: "face-imp-trick.img",
        sound: "trick_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_trick_m9: {
        type: "emote",
        texture: "face-imp-trick.img",
        sound: "trick_03",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_trick_chatty: {
        type: "emote",
        texture: "face-imp-trick.img",
        sound: "trick_02",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_trick_drain: {
        type: "emote",
        texture: "face-imp-trick.img",
        sound: "trick_02",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_treat_9mm: {
        type: "emote",
        texture: "face-angel-treat.img",
        sound: "treat_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_treat_12g: {
        type: "emote",
        texture: "face-angel-treat.img",
        sound: "treat_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_treat_556: {
        type: "emote",
        texture: "face-angel-treat.img",
        sound: "treat_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_treat_762: {
        type: "emote",
        texture: "face-angel-treat.img",
        sound: "treat_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_treat_super: {
        type: "emote",
        texture: "face-angel-treat.img",
        sound: "treat_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Locked,
    },
    emote_bugle_inspiration_red: {
        type: "emote",
        texture: "bugle-inspiration-red.img",
        sound: "emote_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Other,
    },
    emote_bugle_final_red: {
        type: "emote",
        texture: "bugle-final-red.img",
        sound: "emote_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Other,
    },
    emote_bugle_inspiration_blue: {
        type: "emote",
        texture: "bugle-inspiration-blue.img",
        sound: "emote_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Other,
    },
    emote_bugle_final_blue: {
        type: "emote",
        texture: "bugle-final-blue.img",
        sound: "emote_01",
        channel: "ui",
        noCustom: true,
        category: EmoteCategory.Other,
    },
    emote_thumbsup: {
        type: "emote",
        name: "Thumbs Up",
        rarity: Rarity.Common,
        texture: "thumbs-up.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_sadface: {
        type: "emote",
        name: "Sad Face",
        rarity: Rarity.Common,
        texture: "face-sad.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_happyface: {
        type: "emote",
        name: "Happy Face",
        rarity: Rarity.Common,
        texture: "face-happy.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_surviv: {
        type: "emote",
        name: "Surviv Logo",
        rarity: Rarity.Common,
        texture: "surviv.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_gg: {
        type: "emote",
        name: "GG",
        rarity: Rarity.Common,
        texture: "gg.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_question: {
        type: "emote",
        name: "Question Mark",
        rarity: Rarity.Common,
        texture: "question.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_tombstone: {
        type: "emote",
        name: "Tombstone",
        rarity: Rarity.Common,
        texture: "tombstone.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_joyface: {
        type: "emote",
        name: "Joyful Face",
        rarity: Rarity.Common,
        texture: "face-joy.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_sobface: {
        type: "emote",
        name: "Sobbing Face",
        rarity: Rarity.Common,
        texture: "face-sob.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_thinkingface: {
        type: "emote",
        name: "Thonk",
        rarity: Rarity.Common,
        texture: "face-thinking.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_flagus: {
        type: "emote",
        name: "Flag United States",
        rarity: Rarity.Common,
        texture: "flag-united-states-of-america.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagthailand: {
        type: "emote",
        name: "Flag Thailand",
        rarity: Rarity.Common,
        texture: "flag-thailand.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaggermany: {
        type: "emote",
        name: "Flag Germany",
        rarity: Rarity.Common,
        texture: "flag-germany.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagfrance: {
        type: "emote",
        name: "Flag France",
        rarity: Rarity.Common,
        texture: "flag-france.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsouthkorea: {
        type: "emote",
        name: "Flag South Korea",
        rarity: Rarity.Common,
        texture: "flag-south-korea.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagbrazil: {
        type: "emote",
        name: "Flag Brazil",
        rarity: Rarity.Common,
        texture: "flag-brazil.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagcanada: {
        type: "emote",
        name: "Flag Canada",
        rarity: Rarity.Common,
        texture: "flag-canada.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagspain: {
        type: "emote",
        name: "Flag Spain",
        rarity: Rarity.Common,
        texture: "flag-spain.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagrussia: {
        type: "emote",
        name: "Flag Russia",
        rarity: Rarity.Common,
        texture: "flag-russia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagmexico: {
        type: "emote",
        name: "Flag Mexico",
        rarity: Rarity.Common,
        texture: "flag-mexico.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagpoland: {
        type: "emote",
        name: "Flag Poland",
        rarity: Rarity.Common,
        texture: "flag-republic-of-poland.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaguk: {
        type: "emote",
        name: "Flag United Kingdom",
        rarity: Rarity.Common,
        texture: "flag-united-kingdom.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagcolombia: {
        type: "emote",
        name: "Flag Colombia",
        rarity: Rarity.Common,
        texture: "flag-colombia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagukraine: {
        type: "emote",
        name: "Flag Ukraine",
        rarity: Rarity.Common,
        texture: "flag-ukraine.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagturkey: {
        type: "emote",
        name: "Flag Turkey",
        rarity: Rarity.Common,
        texture: "flag-turkey.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagphilippines: {
        type: "emote",
        name: "Flag Philippines",
        rarity: Rarity.Common,
        texture: "flag-philippines.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagczechia: {
        type: "emote",
        name: "Flag Czechia",
        rarity: Rarity.Common,
        texture: "flag-czech-republic.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagperu: {
        type: "emote",
        name: "Flag Peru",
        rarity: Rarity.Common,
        texture: "flag-peru.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagaustria: {
        type: "emote",
        name: "Flag Austria",
        rarity: Rarity.Common,
        texture: "flag-austria.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagargentina: {
        type: "emote",
        name: "Flag Argentina",
        rarity: Rarity.Common,
        texture: "flag-argentina.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagjapan: {
        type: "emote",
        name: "Flag Japan",
        rarity: Rarity.Common,
        texture: "flag-japan.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagvenezuela: {
        type: "emote",
        name: "Flag Venezuela",
        rarity: Rarity.Common,
        texture: "flag-venezuela.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagvietnam: {
        type: "emote",
        name: "Flag Vietnam",
        rarity: Rarity.Common,
        texture: "flag-vietnam.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagswitzerland: {
        type: "emote",
        name: "Flag Switzerland",
        rarity: Rarity.Common,
        texture: "flag-switzerland.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagnetherlands: {
        type: "emote",
        name: "Flag Netherlands",
        rarity: Rarity.Common,
        texture: "flag-netherlands.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagchina: {
        type: "emote",
        name: "Flag China",
        rarity: Rarity.Common,
        texture: "flag-china.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagtaiwan: {
        type: "emote",
        name: "Flag Taiwan",
        rarity: Rarity.Common,
        texture: "flag-taiwan.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagchile: {
        type: "emote",
        name: "Flag Chile",
        rarity: Rarity.Common,
        texture: "flag-chile.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagaustralia: {
        type: "emote",
        name: "Flag Australia",
        rarity: Rarity.Common,
        texture: "flag-australia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagdenmark: {
        type: "emote",
        name: "Flag Denmark",
        rarity: Rarity.Common,
        texture: "flag-denmark.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagitaly: {
        type: "emote",
        name: "Flag Italy",
        rarity: Rarity.Common,
        texture: "flag-italy.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsweden: {
        type: "emote",
        name: "Flag Sweden",
        rarity: Rarity.Common,
        texture: "flag-sweden.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagecuador: {
        type: "emote",
        name: "Flag Ecuador",
        rarity: Rarity.Common,
        texture: "flag-ecuador.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagslovakia: {
        type: "emote",
        name: "Flag Slovakia",
        rarity: Rarity.Common,
        texture: "flag-slovakia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaghungary: {
        type: "emote",
        name: "Flag Hungary",
        rarity: Rarity.Common,
        texture: "flag-hungary.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagromania: {
        type: "emote",
        name: "Flag Romania",
        rarity: Rarity.Common,
        texture: "flag-romania.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaghongkong: {
        type: "emote",
        name: "Flag Hong Kong",
        rarity: Rarity.Common,
        texture: "flag-hong-kong.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagindonesia: {
        type: "emote",
        name: "Flag Indonesia",
        rarity: Rarity.Common,
        texture: "flag-indonesia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagfinland: {
        type: "emote",
        name: "Flag Finland",
        rarity: Rarity.Common,
        texture: "flag-finland.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagnorway: {
        type: "emote",
        name: "Flag Norway",
        rarity: Rarity.Common,
        texture: "flag-norway.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagbosnia: {
        type: "emote",
        name: "Flag Bosnia",
        rarity: Rarity.Common,
        texture: "flag-bosnia-and-herzegovina.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaglibya: {
        type: "emote",
        name: "Flag Libya",
        rarity: Rarity.Common,
        texture: "flag-libya.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_heart: {
        type: "emote",
        name: "Heart",
        rarity: Rarity.Common,
        texture: "heart.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_sleepy: {
        type: "emote",
        name: "Zzz",
        rarity: Rarity.Common,
        texture: "sleepy.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_flex: {
        type: "emote",
        name: "Flex",
        rarity: Rarity.Common,
        texture: "flex.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_angryface: {
        type: "emote",
        name: "Angry Face",
        rarity: Rarity.Common,
        texture: "face-angry.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_upsidedownface: {
        type: "emote",
        name: "Upside Down Face",
        rarity: Rarity.Common,
        texture: "face-upsidedown.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_teabag: {
        type: "emote",
        name: "Teabag",
        rarity: Rarity.Common,
        texture: "teabag.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_alienface: {
        type: "emote",
        name: "Alien Face",
        rarity: Rarity.Common,
        texture: "face-alien.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_flagbelarus: {
        type: "emote",
        name: "Flag Belarus",
        rarity: Rarity.Common,
        texture: "flag-belarus.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagbelgium: {
        type: "emote",
        name: "Flag Belgium",
        rarity: Rarity.Common,
        texture: "flag-belgium.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagkazakhstan: {
        type: "emote",
        name: "Flag Kazakhstan",
        rarity: Rarity.Common,
        texture: "flag-kazakhstan.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_egg: {
        type: "emote",
        name: "Egg",
        rarity: Rarity.Common,
        texture: "egg.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_police: {
        type: "emote",
        name: "Police Insignia",
        rarity: Rarity.Common,
        texture: "police.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_dabface: {
        type: "emote",
        name: "Dab Face",
        rarity: Rarity.Common,
        texture: "face-dab.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_flagmalaysia: {
        type: "emote",
        name: "Flag Malaysia",
        rarity: Rarity.Common,
        texture: "flag-malaysia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagnewzealand: {
        type: "emote",
        name: "Flag New Zealand",
        rarity: Rarity.Common,
        texture: "flag-new-zealand.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_logosurviv: {
        type: "emote",
        name: "PARMA",
        rarity: Rarity.Common,
        texture: "logo-surviv.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_logoegg: {
        type: "emote",
        name: "The Egg",
        rarity: Rarity.Common,
        texture: "logo-egg.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_logoswine: {
        type: "emote",
        name: "The Swine",
        rarity: Rarity.Common,
        texture: "logo-swine.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_logohydra: {
        type: "emote",
        name: "The Hydra",
        rarity: Rarity.Common,
        texture: "logo-hydra.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_logostorm: {
        type: "emote",
        name: "The Storm",
        rarity: Rarity.Common,
        texture: "logo-storm.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_flaghonduras: {
        type: "emote",
        name: "Flag Honduras",
        rarity: Rarity.Common,
        texture: "flag-honduras.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_logocaduceus: {
        type: "emote",
        name: "The Caduceus",
        rarity: Rarity.Common,
        texture: "logo-caduceus.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_impface: {
        type: "emote",
        name: "Imp Face",
        rarity: Rarity.Common,
        texture: "face-imp.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_monocleface: {
        type: "emote",
        name: "Monocole Face",
        rarity: Rarity.Common,
        texture: "face-monocle.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_sunglassface: {
        type: "emote",
        name: "Sunglasses Face",
        rarity: Rarity.Common,
        texture: "face-sunglass.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_headshotface: {
        type: "emote",
        name: "Headshot!",
        rarity: Rarity.Common,
        texture: "face-headshot.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_potato: {
        type: "emote",
        name: "Potato",
        rarity: Rarity.Common,
        texture: "potato.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_cake: {
        type: "emote",
        name: "Cake",
        rarity: Rarity.Common,
        texture: "cake.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_leek: {
        type: "emote",
        name: "Leek",
        rarity: Rarity.Common,
        texture: "leek.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_eggplant: {
        type: "emote",
        name: "Eggplant",
        rarity: Rarity.Common,
        texture: "eggplant.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_baguette: {
        type: "emote",
        name: "Baguette",
        rarity: Rarity.Common,
        texture: "baguette.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_chick: {
        type: "emote",
        name: "Chick",
        rarity: Rarity.Common,
        texture: "chick.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_flagbolivia: {
        type: "emote",
        name: "Flag Bolivia",
        rarity: Rarity.Common,
        texture: "flag-bolivia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagcroatia: {
        type: "emote",
        name: "Flag Croatia",
        rarity: Rarity.Common,
        texture: "flag-croatia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagindia: {
        type: "emote",
        name: "Flag India",
        rarity: Rarity.Common,
        texture: "flag-india.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagisrael: {
        type: "emote",
        name: "Flag Israel",
        rarity: Rarity.Common,
        texture: "flag-israel.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaggeorgia: {
        type: "emote",
        name: "Flag Georgia",
        rarity: Rarity.Common,
        texture: "flag-georgia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaggreece: {
        type: "emote",
        name: "Flag Greece",
        rarity: Rarity.Common,
        texture: "flag-greece.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagguatemala: {
        type: "emote",
        name: "Flag Gautemala",
        rarity: Rarity.Common,
        texture: "flag-guatemala.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagportugal: {
        type: "emote",
        name: "Flag Portugal",
        rarity: Rarity.Common,
        texture: "flag-portugal.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagserbia: {
        type: "emote",
        name: "Flag Serbia",
        rarity: Rarity.Common,
        texture: "flag-serbia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagsingapore: {
        type: "emote",
        name: "Flag Singapore",
        rarity: Rarity.Common,
        texture: "flag-singapore.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagtrinidad: {
        type: "emote",
        name: "Flag Trinidad and Tobago",
        rarity: Rarity.Common,
        texture: "flag-trinidad-and-tobago.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaguruguay: {
        type: "emote",
        name: "Flag Uruguay",
        rarity: Rarity.Common,
        texture: "flag-uruguay.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_logoconch: {
        type: "emote",
        name: "The Conch",
        rarity: Rarity.Common,
        texture: "logo-conch.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_pineapple: {
        type: "emote",
        name: "Pineapple",
        rarity: Rarity.Common,
        texture: "pineapple.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_coconut: {
        type: "emote",
        name: "Coconut",
        rarity: Rarity.Common,
        texture: "coconut.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_crab: {
        type: "emote",
        name: "Crab",
        rarity: Rarity.Common,
        texture: "crab.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Animals,
    },
    emote_whale: {
        type: "emote",
        name: "Whale",
        rarity: Rarity.Common,
        texture: "whale.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Animals,
    },
    emote_logometeor: {
        type: "emote",
        name: "The Meteor",
        rarity: Rarity.Common,
        texture: "logo-meteor.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_salt: {
        type: "emote",
        name: "Salt Shaker",
        rarity: Rarity.Common,
        texture: "salt.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_disappointface: {
        type: "emote",
        name: "Disappointed Face",
        rarity: Rarity.Common,
        texture: "face-disappoint.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_logocrossing: {
        type: "emote",
        name: "The Crossing",
        rarity: Rarity.Common,
        texture: "logo-crossing.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_fish: {
        type: "emote",
        name: "Fish",
        rarity: Rarity.Common,
        texture: "fish.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Animals,
    },
    emote_campfire: {
        type: "emote",
        name: "Campfire",
        rarity: Rarity.Common,
        texture: "campfire.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_chickendinner: {
        type: "emote",
        name: "Chicken Dinner",
        rarity: Rarity.Common,
        texture: "chicken-dinner.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_cattle: {
        type: "emote",
        name: "Cattle Skull",
        rarity: Rarity.Common,
        texture: "cattle.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Animals,
    },
    emote_icecream: {
        type: "emote",
        name: "Ice Cream",
        rarity: Rarity.Common,
        texture: "ice-cream.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_cupcake: {
        type: "emote",
        name: "Cupcake",
        rarity: Rarity.Common,
        texture: "cupcake.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_donut: {
        type: "emote",
        name: "Donut",
        rarity: Rarity.Common,
        texture: "donut.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_logohatchet: {
        type: "emote",
        name: "The Hatchet",
        rarity: Rarity.Common,
        texture: "logo-hatchet.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_acorn: {
        type: "emote",
        name: "Acorn",
        rarity: Rarity.Common,
        texture: "acorn.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_trunk: {
        type: "emote",
        name: "Tree Trunk",
        rarity: Rarity.Common,
        texture: "trunk.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_forest: {
        type: "emote",
        name: "Forest",
        rarity: Rarity.Common,
        texture: "forest.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_pumpkin: {
        type: "emote",
        name: "Pumpkin",
        rarity: Rarity.Common,
        texture: "pumpkin.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_candycorn: {
        type: "emote",
        name: "Candy Corn",
        rarity: Rarity.Common,
        texture: "candy-corn.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_pilgrimhat: {
        type: "emote",
        name: "Pilgrim",
        rarity: Rarity.Common,
        texture: "pilgrim-hat.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_turkeyanimal: {
        type: "emote",
        name: "Turkey",
        rarity: Rarity.Common,
        texture: "turkey-animal.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Animals,
    },
    emote_heartface: {
        type: "emote",
        name: "Heart Face",
        rarity: Rarity.Common,
        texture: "face-heart.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_logochrysanthemum: {
        type: "emote",
        name: "The Chrysanthemum",
        rarity: Rarity.Common,
        texture: "logo-chrysanthemum.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_santahat: {
        type: "emote",
        name: "Santa Hat",
        rarity: Rarity.Common,
        texture: "santa-hat.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_snowman: {
        type: "emote",
        name: "Snowman",
        rarity: Rarity.Common,
        texture: "snowman.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_snowflake: {
        type: "emote",
        name: "Snowflake",
        rarity: Rarity.Common,
        texture: "snowflake.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_flagmorocco: {
        type: "emote",
        name: "Flag Morocco",
        rarity: Rarity.Common,
        texture: "flag-morocco.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagestonia: {
        type: "emote",
        name: "Flag Estonia",
        rarity: Rarity.Common,
        texture: "flag-estonia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagalgeria: {
        type: "emote",
        name: "Flag Algeria",
        rarity: Rarity.Common,
        texture: "flag-algeria.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagegypt: {
        type: "emote",
        name: "Flag Egypt",
        rarity: Rarity.Common,
        texture: "flag-egypt.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagazerbaijan: {
        type: "emote",
        name: "Flag Azerbaijan",
        rarity: Rarity.Common,
        texture: "flag-azerbaijan.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagalbania: {
        type: "emote",
        name: "Flag Albania",
        rarity: Rarity.Common,
        texture: "flag-albania.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaglithuania: {
        type: "emote",
        name: "Flag Lithuania",
        rarity: Rarity.Common,
        texture: "flag-lithuania.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaglatvia: {
        type: "emote",
        name: "Flag Latvia",
        rarity: Rarity.Common,
        texture: "flag-latvia.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaguae: {
        type: "emote",
        name: "Flag United Arab Emirates",
        rarity: Rarity.Common,
        texture: "flag-united-arab-emirates.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagdominicanrepublic: {
        type: "emote",
        name: "Flag Dominican Republic",
        rarity: Rarity.Common,
        texture: "flag-dominican-republic.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagpalestine: {
        type: "emote",
        name: "Flag Palestine",
        rarity: Rarity.Common,
        texture: "flag-palestine.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagtransgender: {
        type: "emote",
        name: "Flag Transgender",
        rarity: Rarity.Common,
        texture: "flag-transgender.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagpride: {
        type: "emote",
        name: "Flag Pride",
        rarity: Rarity.Common,
        texture: "flag-pride.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaglesbian: {
        type: "emote",
        name: "Flag Lesbian",
        rarity: Rarity.Common,
        texture: "flag-lesbian.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flaggay: {
        type: "emote",
        name: "Flag Gay",
        rarity: Rarity.Common,
        texture: "flag-gay.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagasexual: {
        type: "emote",
        name: "Flag Asexual",
        rarity: Rarity.Common,
        texture: "flag-asexual.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_flagnonbinary: {
        type: "emote",
        name: "Flag Non-Binary",
        rarity: Rarity.Common,
        texture: "flag-nonbinary.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_logocloud: {
        type: "emote",
        name: "The Cloud",
        rarity: Rarity.Common,
        texture: "logo-cloud.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_ghost_base: {
        type: "emote",
        name: "Ghost",
        rarity: Rarity.Uncommon,
        texture: "ghost-base.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_bandagedface: {
        type: "emote",
        name: "Bandaged Face",
        rarity: Rarity.Uncommon,
        texture: "face-bandaged.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_picassoface: {
        type: "emote",
        name: "Picasso Face",
        rarity: Rarity.Uncommon,
        texture: "face-picasso.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_pooface: {
        type: "emote",
        name: "Poo Face",
        rarity: Rarity.Rare,
        texture: "face-poo.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_ok: {
        type: "emote",
        name: "Ok",
        rarity: Rarity.Uncommon,
        texture: "ok.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_relief: {
        type: "emote",
        name: "Relief",
        rarity: Rarity.Common,
        texture: "relief.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_rainbow: {
        type: "emote",
        name: "Rainbow",
        rarity: Rarity.Rare,
        texture: "rainbow.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_logotwins: {
        type: "emote",
        name: "The Twins",
        rarity: Rarity.Common,
        texture: "logo-twins.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_chimpion: {
        type: "emote",
        name: "Chimpion",
        rarity: Rarity.Epic,
        texture: "emote-chimpion01.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Animals,
    },
    emote_rip: {
        type: "emote",
        name: "RIP",
        rarity: Rarity.Epic,
        texture: "loot-rip-emote.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
        isAnimated: true,
        animationSpeed: 0.2,
        animationScale: 0.5,
        sprites: [
            "emote-rip-01.img",
            "emote-rip-02.img",
            "emote-rip-03.img",
            "emote-rip-04.img",
            "emote-rip-05.img",
            "emote-rip-06.img",
            "emote-rip-07.img",
            "emote-rip-08.img",
            "emote-rip-09.img",
            "emote-rip-10.img",
            "emote-rip-11.img",
            "emote-rip-12.img",
            "emote-rip-13.img",
            "emote-rip-14.img",
            "emote-rip-14.img",
            "emote-rip-14.img",
            "emote-rip-14.img",
            "emote-rip-14.img",
            "emote-rip-14.img",
            "emote-rip-14.img",
        ],
    },
    emote_pay_respects: {
        type: "emote",
        name: "Pay Respects",
        rarity: Rarity.Epic,
        texture: "loot-pay-respects-emote.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
        isAnimated: true,
        animationSpeed: 0.2,
        animationScale: 0.5,
        sprites: [
            "emote-pay-respects-01.img",
            "emote-pay-respects-02.img",
            "emote-pay-respects-03.img",
            "emote-pay-respects-04.img",
            "emote-pay-respects-05.img",
            "emote-pay-respects-06.img",
            "emote-pay-respects-07.img",
            "emote-pay-respects-08.img",
            "emote-pay-respects-09.img",
            "emote-pay-respects-10.img",
            "emote-pay-respects-11.img",
            "emote-pay-respects-12.img",
            "emote-pay-respects-13.img",
            "emote-pay-respects-14.img",
            "emote-pay-respects-15.img",
            "emote-pay-respects-16.img",
            "emote-pay-respects-16.img",
            "emote-pay-respects-16.img",
            "emote-pay-respects-16.img",
            "emote-pay-respects-16.img",
        ],
    },
    emote_shur: {
        type: "emote",
        name: "Shuriken",
        rarity: Rarity.Common,
        texture: "emote-shur.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
        isAnimated: true,
        animationSpeed: 0.14,
        animationScale: 0.5,
        sprites: [
            "shur1.img",
            "shur2.img",
            "shur3.img",
            "shur4.img",
            "shur5.img",
            "shur6.img",
            "shur7.img",
            "shur8.img",
            "shur9.img",
            "shur10.img",
            "shur11.img",
            "shur12.img",
        ],
    },
    emote_too_close: {
        type: "emote",
        name: "Too Close",
        rarity: Rarity.Common,
        texture: "emote-too-close01.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_fabulorn: {
        type: "emote",
        name: "Fabulorn",
        rarity: Rarity.Mythic,
        texture: "emote-fabulorn.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
        isAnimated: true,
        animationSpeed: 0.1,
        animationScale: 0.5,
        sprites: [
            "fabulorn1.img",
            "fabulorn2.img",
            "fabulorn3.img",
            "fabulorn4.img",
            "fabulorn5.img",
            "fabulorn6.img",
            "fabulorn7.img",
            "fabulorn8.img",
        ],
    },
    emote_mr_sockey: {
        type: "emote",
        name: "Mr Sockey",
        rarity: Rarity.Epic,
        texture: "emote-mr-sockey01.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
        isAnimated: true,
        animationSpeed: 0.2,
        animationScale: 0.5,
        sprites: [
            "emote-mr-sockey01.img",
            "emote-mr-sockey02.img",
            "emote-mr-sockey03.img",
            "emote-mr-sockey04.img",
            "emote-mr-sockey05.img",
            "emote-mr-sockey06.img",
            "emote-mr-sockey07.img",
            "emote-mr-sockey08.img",
            "emote-mr-sockey09.img",
            "emote-mr-sockey10.img",
            "emote-mr-sockey01.img",
            "emote-mr-sockey02.img",
            "emote-mr-sockey03.img",
            "emote-mr-sockey04.img",
            "emote-mr-sockey05.img",
            "emote-mr-sockey06.img",
            "emote-mr-sockey07.img",
            "emote-mr-sockey08.img",
            "emote-mr-sockey09.img",
            "emote-mr-sockey10.img",
        ],
    },
    emote_friend_ghost: {
        type: "emote",
        name: "Friendly Ghost",
        rarity: Rarity.Rare,
        texture: "emote-friend-ghost01.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
        isAnimated: true,
        animationSpeed: 0.2,
        animationScale: 0.5,
        sprites: [
            "emote-friend-ghost01.img",
            "emote-friend-ghost01.img",
            "emote-friend-ghost01.img",
            "emote-friend-ghost01.img",
            "emote-friend-ghost02.img",
            "emote-friend-ghost03.img",
            "emote-friend-ghost04.img",
            "emote-friend-ghost05.img",
            "emote-friend-ghost06.img",
            "emote-friend-ghost07.img",
            "emote-friend-ghost08.img",
            "emote-friend-ghost09.img",
            "emote-friend-ghost10.img",
            "emote-friend-ghost11.img",
            "emote-friend-ghost12.img",
            "emote-friend-ghost13.img",
            "emote-friend-ghost14.img",
            "emote-friend-ghost14.img",
            "emote-friend-ghost14.img",
            "emote-friend-ghost14.img",
        ],
    },
    emote_six_seven: {
        type: "emote",
        name: "67",
        rarity: Rarity.Rare,
        texture: "loot-67-emote.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
        isAnimated: true,
        animationSpeed: 0.2,
        animationScale: 0.5,
        sprites: [
            "face-67-1.img",
            "face-67-2.img",
            "face-67-3.img",
            "face-67-4.img",
            "face-67-5.img",
            "face-67-6.img",
            "face-67-7.img",
            "face-67-8.img",
        ],
    },
    emote_angry_blob: {
        type: "emote",
        name: "Angry Blob",
        rarity: Rarity.Rare,
        texture: "emote-angry-blob.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_boffy: {
        type: "emote",
        name: "Boffy",
        rarity: Rarity.Rare,
        texture: "boffy.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_clown: {
        type: "emote",
        name: "Clown",
        rarity: Rarity.Rare,
        texture: "emote-clown.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_deadface: {
        type: "emote",
        name: "Dead Face",
        rarity: Rarity.Rare,
        texture: "emote-deadface.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_easy: {
        type: "emote",
        name: "Easy",
        rarity: Rarity.Common,
        texture: "emote-easy.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_eye: {
        type: "emote",
        name: "Eye",
        rarity: Rarity.Common,
        texture: "emote-eye.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Logos,
    },
    emote_flushed: {
        type: "emote",
        name: "Flushed",
        rarity: Rarity.Rare,
        texture: "emote-flushed.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_frustration: {
        type: "emote",
        name: "Frustration",
        rarity: Rarity.Uncommon,
        texture: "emote-frustration.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_glasses: {
        type: "emote",
        name: "Glasses",
        rarity: Rarity.Rare,
        texture: "emote-glasses.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_gogo: {
        type: "emote",
        name: "Gogo",
        rarity: Rarity.Common,
        texture: "emote-gogo.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_greedy: {
        type: "emote",
        name: "Greedy",
        rarity: Rarity.Common,
        texture: "emote-greedy.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_happyghost: {
        type: "emote",
        name: "Happy Ghost",
        rarity: Rarity.Epic,
        texture: "emote-happyghost.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_hi5: {
        type: "emote",
        name: "Hi5",
        rarity: Rarity.Common,
        texture: "emote-hi5.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_lies: {
        type: "emote",
        name: "Lies",
        rarity: Rarity.Uncommon,
        texture: "emote-lies.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_neutral: {
        type: "emote",
        name: "Neutral",
        rarity: Rarity.Rare,
        texture: "emote-neutral.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_nooblet: {
        type: "emote",
        name: "Nooblet",
        rarity: Rarity.Rare,
        texture: "emote-nooblet.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_nutz: {
        type: "emote",
        name: "Nutz",
        rarity: Rarity.Rare,
        texture: "emote-nutz.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_oof: {
        type: "emote",
        name: "Oof",
        rarity: Rarity.Common,
        texture: "emote-oof.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_panned: {
        type: "emote",
        name: "Panned",
        rarity: Rarity.Rare,
        texture: "emote-panned.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_pills: {
        type: "emote",
        name: "Pills",
        rarity: Rarity.Epic,
        texture: "emote-pills.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_puke: {
        type: "emote",
        name: "Puke",
        rarity: Rarity.Rare,
        texture: "emote-puke.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_pwn: {
        type: "emote",
        name: "Pwn",
        rarity: Rarity.Common,
        texture: "emote-pwn.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_qq: {
        type: "emote",
        name: "QQ",
        rarity: Rarity.Common,
        texture: "emote-qq.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_shockface: {
        type: "emote",
        name: "Shock & Awe",
        rarity: Rarity.Common,
        texture: "face-shock.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_shroomcloud: {
        type: "emote",
        name: "Shroomcloud",
        rarity: Rarity.Epic,
        texture: "emote-shroomcloud.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_skull: {
        type: "emote",
        name: "Skull",
        rarity: Rarity.Rare,
        texture: "emote-skull.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_starstruck: {
        type: "emote",
        name: "Starstruck",
        rarity: Rarity.Rare,
        texture: "emote-starstruck.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_sushi_roll: {
        type: "emote",
        name: "Sushi Roll",
        rarity: Rarity.Mythic,
        texture: "emote-sushi-roll.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Food,
    },
    emote_sweaty: {
        type: "emote",
        name: "Sweaty",
        rarity: Rarity.Uncommon,
        texture: "emote-sweaty.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_taunty: {
        type: "emote",
        name: "Taunty",
        rarity: Rarity.Rare,
        texture: "emote-taunty.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_trollface: {
        type: "emote",
        name: "Trollface",
        rarity: Rarity.Epic,
        texture: "emote-trollface.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_wait: {
        type: "emote",
        name: "Wait",
        rarity: Rarity.Common,
        texture: "emote-wait.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_bagged: {
        type: "emote",
        name: "Bagged",
        rarity: Rarity.Common,
        texture: "emote-bagged.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_buuurn: {
        type: "emote",
        name: "Buuurn",
        rarity: Rarity.Common,
        texture: "emote-buuurn05.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_chickend: {
        type: "emote",
        name: "Chicken'd",
        rarity: Rarity.Common,
        texture: "emote-chickend.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Animals,
    },
    emote_dove: {
        type: "emote",
        name: "Dove",
        rarity: Rarity.Common,
        texture: "emote-dove02.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Animals,
    },
    emote_dynaboom: {
        type: "emote",
        name: "Dynaboom",
        rarity: Rarity.Uncommon,
        texture: "emote-dynaboom.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_golden_bullet: {
        type: "emote",
        name: "Golden Bullet",
        rarity: Rarity.Rare,
        texture: "emote-golden-bullet.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_horsin_zone: {
        type: "emote",
        name: "Horsin' Zone",
        rarity: Rarity.Uncommon,
        texture: "emote-horsin-zone.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Animals,
    },
    emote_i_heart_you: {
        type: "emote",
        name: "I Heart You",
        rarity: Rarity.Uncommon,
        texture: "emote-i-heart-you.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_loot_bones: {
        type: "emote",
        name: "Loot Bones",
        rarity: Rarity.Uncommon,
        texture: "emote-loot-bones.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_lootloot: {
        type: "emote",
        name: "Loot Loot",
        rarity: Rarity.Common,
        texture: "emote-lootloot01.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_new_in_town: {
        type: "emote",
        name: "New In Town",
        rarity: Rarity.Common,
        texture: "emote-new-in-town.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_old_respects: {
        type: "emote",
        name: "Old Respects",
        rarity: Rarity.Uncommon,
        texture: "emote-old-respects.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_prickly_business: {
        type: "emote",
        name: "Prickly Business",
        rarity: Rarity.Common,
        texture: "emote-prickly-business.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_puke_rainbow: {
        type: "emote",
        name: "Puke Rainbow",
        rarity: Rarity.Rare,
        texture: "emote-puke-rainbow.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_rad: {
        type: "emote",
        name: "Rad",
        rarity: Rarity.Common,
        texture: "emote-rad.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_radical_ray: {
        type: "emote",
        name: "Radical Ray",
        rarity: Rarity.Uncommon,
        texture: "emote-radical-ray.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_rainy_day: {
        type: "emote",
        name: "Rainy Day",
        rarity: Rarity.Common,
        texture: "emote-rainy-day01.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_rawr: {
        type: "emote",
        name: "Rawr",
        rarity: Rarity.Common,
        texture: "emote-rawr.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Animals,
    },
    emote_send_some_potis: {
        type: "emote",
        name: "Send Some Potis",
        rarity: Rarity.Common,
        texture: "emote-send-some-potis.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_tiny_turtle: {
        type: "emote",
        name: "Tiny Turtle",
        rarity: Rarity.Common,
        texture: "emote-tiny-turtle01.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Animals,
    },
    emote_tongues_out: {
        type: "emote",
        name: "Tongues Out",
        rarity: Rarity.Common,
        texture: "emote-tongues-out.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_was_a_lovely_cow: {
        type: "emote",
        name: "Was A Lovely Cow",
        rarity: Rarity.Common,
        texture: "emote-was-a-lovely-cow.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Animals,
    },
    emote_wth: {
        type: "emote",
        name: "WTH",
        rarity: Rarity.Common,
        texture: "emote-wth.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Faces,
    },
    emote_yeehaw: {
        type: "emote",
        name: "Yeehaw",
        rarity: Rarity.Common,
        texture: "emote-yeehaw.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_you_invader: {
        type: "emote",
        name: "You Invader",
        rarity: Rarity.Common,
        texture: "emote-you-invader.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
    emote_flagmoldova: {
        type: "emote",
        name: "Flag Moldova",
        rarity: Rarity.Stock,
        texture: "flag-moldova.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Flags,
    },
    emote_its_ok: {
        type: "emote",
        name: "Its Ok",
        rarity: Rarity.Common,
        texture: "its_ok.img",
        sound: "emote_01",
        channel: "ui",
        teamOnly: false,
        category: EmoteCategory.Other,
    },
};
