import { Rarity } from "../../gameConfig";

export type LootBoxChance = {
    rarity: Rarity;
    weight: number;
};

export type LootBoxDef = {
    id: string;
    name: string;
    price: number;
    source: string;
    chances: LootBoxChance[];
    itemPools: Partial<Record<Rarity, string[]>>;
};

export const lootBoxDefs = {
    loot_box_01: {
        id: "loot_box_01",
        name: "PARMA Crate",
        price: 100,
        source: "PARMA Crate",
        chances: [
            { rarity: Rarity.Common, weight: 60 },
            { rarity: Rarity.Uncommon, weight: 24 },
            { rarity: Rarity.Rare, weight: 10 },
            { rarity: Rarity.Epic, weight: 5 },
            { rarity: Rarity.Mythic, weight: 1 },
        ],
        itemPools: {
            [Rarity.Common]: [
                "outfitParma",
                "heal_heart",
                "boost_star",
                "death_toon_blast",
                "emote_relief",
                "outfitWhite",
                "outfitWoodland",
                "outfitKeyLime",
                "outfitCobaltShell",
                "outfitDarkGloves",
                "outfitDesertCamo",
                "outfitCamo",
                "outfitBlackIce",
                "outfitCoconut",
                "emote_logotwins",
                "fist_blueVelvet",
                "fist_immolate",
                "fist_bulletbills",
                "knuckles_rusted",
            ],
            [Rarity.Uncommon]: [
                "emote_bandagedface",
                "emote_ghost_base",
                "emote_picassoface",
                "emote_ok",
                "outfitCarbonFiber",
                "outfitRed",
                "outfitSnow",
                "heal_moon",
                "boost_naturalize",
                "fist_split",
                "fist_ranger",
                "fist_linedUp",
            ],
            [Rarity.Rare]: [
                "emote_pooface",
                "emote_rainbow",
                "heal_tomoe",
                "boost_shuriken",
                "outfitTurkey",
                "outfitSplotchfest",
                "bayonet_rugged",
                "karambit_rugged",
                "huntsman_rugged",
                "bowie_vintage",
                "death_turkey_feathers",
                "death_cupid",
            ],
            [Rarity.Epic]: [
                "knuckles_heroic",
                "fist_frostpunch",
                "death_blood_explosion",
                "death_black_hole",
                "huntsman_burnished",
                "bowie_frontier",
                "emote_trollface",
                "emote_rip",
                "emote_pay_respects",
            ],
            [Rarity.Mythic]: [
                "outfitChromesis",
                "bayonet_woodland",
                "death_confetti",
                "death_sparkle",
                "emote_fabulorn",
                "emote_sushi_roll",
            ],
        },
    },
    loot_box_02: {
        id: "loot_box_02",
        name: "HYDRA Crate",
        price: 250,
        source: "HYDRA Crate",
        chances: [
            { rarity: Rarity.Common, weight: 4 },
            { rarity: Rarity.Uncommon, weight: 42 },
            { rarity: Rarity.Rare, weight: 28 },
            { rarity: Rarity.Epic, weight: 20 },
            { rarity: Rarity.Mythic, weight: 6 },
        ],
        itemPools: {
            [Rarity.Common]: [
                "emote_logohydra",
                "emote_relief",
                "emote_logotwins",
                "boost_star",
                "outfitWoodland",
                "death_toon_blast",
                "outfitBlackIce",
                "fist_blueVelvet",
            ],
            [Rarity.Uncommon]: [
                "outfitCarbonFiber",
                "outfitRed",
                "outfitSnow",
                "heal_moon",
                "boost_naturalize",
                "emote_bandagedface",
                "emote_picassoface",
                "emote_ghost_base",
                "emote_ok",
                "fist_split",
                "fist_ranger",
                "fist_linedUp",
            ],
            [Rarity.Rare]: [
                "emote_pooface",
                "emote_rainbow",
                "heal_tomoe",
                "boost_shuriken",
                "outfitTurkey",
                "outfitSplotchfest",
                "bayonet_rugged",
                "karambit_rugged",
                "huntsman_rugged",
                "bowie_vintage",
                "death_turkey_feathers",
                "death_cupid",
            ],
            [Rarity.Epic]: [
                "knuckles_heroic",
                "emote_trollface",
                "fist_frostpunch",
                "death_blood_explosion",
                "death_potato",
                "huntsman_burnished",
                "bowie_frontier",
                "emote_rip",
                "emote_pay_respects",
            ],
            [Rarity.Mythic]: [
                "outfitChromesis",
                "death_confetti",
                "death_billionaire",
                "bayonet_woodland",
                "emote_fabulorn",
                "emote_sushi_roll",
            ],
        },
    },
    loot_box_03: {
        id: "loot_box_03",
        name: "REDACTED Crate",
        price: 700,
        source: "REDACTED Crate",
        chances: [
            { rarity: Rarity.Common, weight: 1 },
            { rarity: Rarity.Uncommon, weight: 4 },
            { rarity: Rarity.Rare, weight: 15 },
            { rarity: Rarity.Epic, weight: 45 },
            { rarity: Rarity.Mythic, weight: 35 },
        ],
        itemPools: {
            [Rarity.Common]: [
                "death_toon_blast",
                "outfitBlackIce",
                "fist_blueVelvet",
                "emote_relief",
                "emote_logotwins",
            ],
            [Rarity.Uncommon]: [
                "outfitCarbonFiber",
                "outfitRed",
                "outfitSnow",
                "heal_moon",
                "emote_bandagedface",
                "emote_picassoface",
                "emote_ghost_base",
                "emote_ok",
                "fist_split",
                "fist_ranger",
                "fist_linedUp",
                "boost_naturalize",
            ],
            [Rarity.Rare]: [
                "outfitTurkey",
                "outfitSplotchfest",
                "bayonet_rugged",
                "karambit_rugged",
                "huntsman_rugged",
                "bowie_vintage",
                "heal_tomoe",
                "boost_shuriken",
                "emote_pooface",
                "emote_rainbow",
                "death_turkey_feathers",
            ],
            [Rarity.Epic]: [
                "knuckles_heroic",
                "emote_trollface",
                "death_blood_explosion",
                "death_black_hole",
                "fist_frostpunch",
                "huntsman_burnished",
                "bowie_frontier",
                "emote_rip",
                "emote_pay_respects",
            ],
            [Rarity.Mythic]: [
                "outfitChromesis",
                "outfitBlueLava",
                "bayonet_woodland",
                "death_confetti",
                "death_billionaire",
                "emote_fabulorn",
                "emote_sushi_roll",
            ],
        },
    },
    loot_box_04: {
        id: "loot_box_04",
        name: "Ad Crate",
        price: 0,
        source: "Ad Crate",
        chances: [
            { rarity: Rarity.Common, weight: 40 },
            { rarity: Rarity.Uncommon, weight: 30 },
            { rarity: Rarity.Rare, weight: 18 },
            { rarity: Rarity.Epic, weight: 9 },
            { rarity: Rarity.Mythic, weight: 3 },
        ],
        itemPools: {
            [Rarity.Common]: [
                "outfitWhite",
                "outfitWoodland",
                "outfitCamo",
                "outfitDesertCamo",
                "outfitCobaltShell",
            ],
            [Rarity.Uncommon]: [
                "outfitRed",
                "outfitSnow",
                "outfitCarbonFiber",
                "outfitMango",
                "outfitUrbanCamo",
            ],
            [Rarity.Rare]: [
                "outfitThePro",
                "outfitBeachCamo",
                "outfitTiki",
                "outfitInfernoCamo",
            ],
            [Rarity.Epic]: ["outfitAstronaut", "outfitKingGalaxy"],
            [Rarity.Mythic]: ["outfitChromesis", "outfitDiamondy", "outfitPolice"],
        },
    },
} satisfies Record<string, LootBoxDef>;
