import { allowedGuns } from "../../deathmatch/loadoutItems";
import { CrosshairDefs } from "./crosshairDefs";

export const privateOutfits = [
    "outfitToilet",
    "outfitGreenEyes",
    "outfitOwnr",
    "outfitShinyGold",
    "outfitPreacher",
    "outfitBoutique",
    "outfitNotEnough",
    "outfitDev",
    "outfitTheSurvivor",
    "outfitStepz",
];

const _allowedHealEffects = ["heal_basic", "boost_basic"];
const _allowedDeathEffects = ["death_none", "death_basic"];
const _allowedStreaks = [
    "streak_rapid_fire",
    "streak_heavy_hitter",
    "streak_juggernaut",
    "streak_dash",
    "streak_samurai",
];
//  const _allowedGunSkins = [
//     "mosin_gilded"
//     "mosin_camo"
// ];
const _featuredBundleUnlocks = [
    "outfitDemo",
    "outfitTank",
    "outfitMedic",
    "outfitScout",
    "outfitSniper",
    "outfitAssault",
    "outfitWheat",
    "outfitRedLeader",
    "outfitBlueLeader",
    "outfitSpetsnaz",
    "outfitLumber",
    "outfitKhaki",
    "outfitWoodland",
    "outfitKeyLime",
    "outfitCobaltShell",
    "outfitDarkShirt",
    "outfitGhillie",
    "outfitDesertCamo",
    "outfitCamo",
    "outfitParma",
    "outfitWhite",
    "outfitDarkGloves",
    "outfitTurkey",
    "outfitWinter",
    "outfitGeometric",
    "outfitMilitary",
    // "outfitWhiteDay",
    "outfitSpeedo",
    "outfitSnowman",
    "outfitChristmasTree",
    "outfitBuckTeeth",
    "outfitPoinsetee",
    "outfitSnowyClaus",
    "outfitCamoDeer",
    "outfitChemisTree",
    "outfitDeepPurple",
    "outfitClaymore",
    "outfitSunset",
    "outfitChromesis",
    "outfitUrbanCamo",
    "outfitGiraffe",
    "outfitRusticSands",
    "outfitWaves",
    "outfitCow",
    "outfitFragtastic",
    "outfitZebra",
    "outfitMango",
    "outfitNeonEyesore",
    "outfitInfernoCamo",
    "outfitParrot",
    "outfitSpeedoSunburn",
    "outfitMojo",
    "outfitBlueLava",
    "outfitCrusader",
    "outfitLasrDisk",
    "outfitBeachCamo",
    "outfitForest",
    "outfitVenom",
    "outfitUnderbrush",
    "outfitMellow",
    "outfitRosePetals",
    "outfitBengal",
    "outfitSortaBlue",
    "outfitPurpleMecha",
    "outfitItJustMist",
    "outfitOneInAMelon",
    "outfitBoet",
    "outfitFullCircle",
    "outfitPanteraOnca",
    "outfitOldKumo",
    "outfitPleasingPart",
    "outfitAvocadoh",
    "outfitTipTheScales",
    "outfitEyes_t",
    "outfitGhoulFire",
    "outfitSunburn",
    "outfitGridflag",
    "outfitStarflag",
    "outfitBubblegum",
    "outfitMelonWater",
    "outfitElectricIce",
    "outfitStarryNight",
    "outfitDragonTails",
    "outfitDigiturt",
    "outfitBraaains",
    "outfitNorseCode",
    "outfitStumped",
    "outfitCosmicBlue",
    "outfitChromaticCTR",
    "outfitTurtleSweater",
    "outfitHowPitaful",
    "outfitSoapPods",
    "outfitTomatoandCheese",
    "outfitH2Oh",
    "outfitSwords",
    "outfitHopelessRamentic",
    "outfitChewieCheese",
    "outfitWoodFire",
    "outfitHoldinHide",
    "outfitDisasteroid",
    "outfitRuppert",
    "outfitBluntRazor",
    "outfitGreenTeaRex",
    "outfitTribeMask",
    "outfitPhoebonachi",
    "outfitTribeShield",
    "outfitBrontoChop",
    "outfitTunelSun",
    "outfitHuedini",
    "outfitBombyman",
    "outfitIdDie4U",
    "outfitIntoTheGrid",
    "outfitBitplosion",
    "oufitItsMeCoin",
    "outfitMaxAttack",
    "outfitHowlODays",
    "outfitCaptnCactus",
    "outfitNachoHat",
    "outfitBroncoSaurus",
    "outfitNeckNapkin",
    "outfitMoosli",
    "outfitSuppaPoncho",
    "outfitGoodFeather",
    "outfitRanchDressing",
    "outfitTheySeeMeRolling",
    "outfitSirLoin",
    "outfitAhoy",
    "outfitLustrousPaladin",
    "outfitYinYang",
    "outfitTiki",
    "outfitMachoLucha2",
    "outfitCalaca",
    "outfitEggnite",
    "outfitSpaceSnout",
    "outfitMugnificent",
    "outfitDeRanged",
    "outfitSnow",
    "outfitBlackIce",
    "outfitCoconut",
    "outfitWave",
    "outfitParrotfish",
    "outfitCheckmate",
    "outfitWolf",
    "outfitRiotPlaid",
    "outfitBugcat",
    "outfitToxicFire",
    "outfitDonut",
    "outfitPolice",
    "outfitPreacher",
    "outfitPanda",
    "outfitDiamond",
    "outfitAero",
    "outfitColdestEdge",
    "outfitPeru",
    "outfitPaintSplat",
    "outfitSacredGeometry",
    "outfitGoldenWaffle",
    "outfitStoneIdol",
    "outfitMissingTexture",
    "outfitVikingHelm",
    "outfitBlush",
    "outfitMondrian",
    "outfitFishBowl",
    "outfitCatchemOl",
    "outfitMeow",
    "outfitPreyDinner",
    "outfitCandyCorn",
    "outfitVitaminD",
];
const _allowedMeleeSkins = [
    "fists",
    "red_gloves",
    "feral_gloves",
    "crab_gloves",
    // "fist_bePresent",
    // "fist_dreidel",
    // "fist_pineFury",
    // "fist_blueVelvet",
    // "fist_split",
    // "fist_frostpunch",
    // "fist_moss",
    // "fist_immolate",
    // "fist_rainbowhands",
    // "fist_bulletbills",
    // "fist_poke",
    // "fist_darklets",
    // "fist_blackholes",
    // "fist_ranger",
    // "fist_ember",
    // "fist_linedUp",
    // "fist_leaf",
    // "fist_scifi",
    // "fist_dinoclaws",
    // "fist_gift_punch",
    // "fist_santa",
    // "fist_purptog",
    // "fist_golden_lobster",
    // "fist_spongeGuy",
    // "fist_tropicana",
    // "fist_rafflesia",
    // "fist_goldDrops",
    // "fist_grizzly",
    // "fist_vitaminC",
    // "fist_cocoNut",
    // "fist_atNet",
    // "fist_beachBallin",
    // "fist_marbleRun",
    // "fist_fritterPunch",
    // "fist_bologna",
    // "fist_inkyBusiness",
    // "fist_bloody",
    // "fist_tigerSeed",
    // "fist_flashy",
    // "fist_theOtherPong",
    // "fist_makeAChoice",
    // "fist_paddle",
    // "fist_condimentium",
    // "fist_orangeLime",
    // "fist_purpleShutter",
    // "fist_shinyJello",
    // "fist_ghostPoke",
    // "fist_washiLamps",
    // "fist_getdowntonite",
    // "fist_milestones",
    // "fist_orangeMintstones",
    // "fist_meteorNite",
    // "fist_bonkbonk",
    // "fist_flamingNucleus",
    // "fist_firstTool",
    // "fist_bullsEye",
    // "fist_fuzzyHooves",
    // "fist_stonedgy",
    // "fist_pixelDots",
    // "fist_retrhorizon",
    // "fist_qFist",
    // "fist_dizzieLocs",
    // "fist_ranchChips",
    // "fist_squareyCerry",
    // "fist_lolitaPop",
    // "fist_developTheseRolls",
    // "fist_dPunchPad",
    // "fist_boogieStripes",
    // "fist_badMitten",
    // "fist_wreckedAngle",
    // "fist_woodyAllan",
    // "fist_tawget",
    // "fist_horsepower",
    // "fist_milkshaked",
    // "fist_cattleBattle",
    // "fist_101spots",
    // "fist_dishSoap",
    // "fist_garbanjo",
    // "fist_graphbars",
    // "fist_lit",
    // "fist_noPineNoGain",
    // "fist_upAndAtom",
    // "fist_watermelon",
    // "fist_living_galaxy",
    // "fist_checkmate",
    // "fist_paws",
    // "fist_acorn",
    // "fist_candyCorn",
    // "fist_ovenMitts",
    // "fist_mapleLeaves",
    // "fist_pinecone",
    // "fist_pumpkin",
    // "fist_skeleton",
    // "fist_turkeyLeg",
    // "knuckles_rusted",
    // "knuckles_heroic",
    // "karambit_rugged",
    // "karambit_prismatic",
    // "karambit_drowned",
    // "bayonet_rugged",
    // "bayonet_woodland",
    // "huntsman_rugged",
    // "huntsman_burnished",
    // "huntsman_blackwater",
    // "bowie_vintage",
    // "bowie_frontier",
    // "karambit_camo",
    // "bayonet_gilded",
    // "carvingfork",
    // "guthook_woodland",
    // "knife_ben",
    // "knife_bone",
    // "knife_toji",
    // "karambit_blazing",
    // "fliptechnical_rugged",
    // "skeleton_knife_rugged",
    // "m9bayonet_autotronic",
    // "m9bayonet_pink",
    // "m9bayonet_rugged",
    // "ursus_jade",
    // "karambit_amethyst",
    // "kunai_shadow",
    // "sickle_farmer",
    // "huntsman_bloodmoon",
];
const _allowedOutfits = [
    "outfitBase",
    // "outfitWheat",
    "outfitNoir",
    "outfitRedLeaderAged",
    "outfitBlueLeaderAged",
    // "outfitSpetsnaz",
    "outfitWoodsCloak",
    "outfitElf",
    "outfitImperial",
    // "outfitLumber",
    "outfitVerde",
    "outfitPineapple",
    "outfitTarkhany",
    "outfitWaterElem",
    "outfitHeaven",
    "outfitMeteor",
    "outfitIslander",
    "outfitAqua",
    "outfitCoral",
    // "outfitKhaki",
    "outfitCasanova",
    "outfitPrisoner",
    "outfitJester",
    // "outfitWoodland",
    "outfitRoyalFortune",
    // "outfitKeyLime",
    // "outfitCobaltShell",
    // "outfitDarkShirt",
    // "outfitDesertCamo",
    // "outfitCamo",
    // "outfitDev",
    // "outfitGD",
    // "outfitMod",
    // "outfitTree",
    // "outfitParma",
    // "outfitWhite",
    "outfitRed",
    // "outfitDarkGloves",
    "outfitCarbonFiber",
    "outfitParmaPrestige",
    // "outfitTurkey",
    // "outfitWinter",
    // "outfitGeometric",
    // "outfitMilitary",
    // "outfitWhiteDay",
    // "outfitSpeedo",
    // "outfitSnowman",
    // "outfitGrinch",
    // "outfitChristmasTree",
    // "outfitBuckTeeth",
    // "outfitPoinsetee",
    // "outfitSnowyClaus",
    // "outfitCamoDeer",
    // "outfitChemisTree",
    // "outfitDeepPurple",
    // "outfitClaymore",
    // "outfitSplotchfest",
    // "outfitSunset",
    // "outfitChromesis",
    // "outfitUrbanCamo",
    // "outfitGiraffe",
    // "outfitRusticSands",
    // "outfitWaves",
    // "outfitCow",
    // "outfitFragtastic",
    // "outfitZebra",
    // "outfitFireball",
    // "outfitMango",
    // "outfitNeonEyesore",
    // "outfitInfernoCamo",
    // "outfitParrot",
    // "outfitSpeedoSunburn",
    // "outfitMojo",
    // "outfitAstronaut",
    // "outfitBlueLava",
    // "outfitCrusader",
    // "outfitLasrDisk",
    // "outfitBeachCamo",
    // "outfitForest",
    // "outfitGingerbread",
    // "outfitVenom",
    // "outfitEventHorizon",
    // "outfitBlueMecha",
    "outfitViper",
    // "outfitUnderbrush",
    // "outfitMellow",
    // "outfitRosePetals",
    // "outfitBengal",
    // "outfitSortaBlue",
    // "outfitPurpleMecha",
    // "outfitMagmatic",
    // "outfitItJustMist",
    // "outfitOneInAMelon",
    // "outfitBoet",
    // "outfitFullCircle",
    // "outfitPanteraOnca",
    // "outfitOldKumo",
    // "outfitRetroSunset",
    // "outfitPleasingPart",
    // "outfitAvocadoh",
    // "outfitTipTheScales",
    // "outfitEyes_t",
    // "outfitGhoulFire",
    // "outfitSunburn",
    // "outfitGridflag",
    // "outfitStarflag",
    // "outfitBubblegum",
    // "outfitMelonWater",
    // "outfitElectricIce",
    // "outfitGaudisque",
    // "outfitToxicBarrel",
    // "outfitStarryNight",
    // "outfitHotMagma",
    // "outfitBlueZone",
    // "outfitKingGalaxy",
    // "outfitDragonTails",
    // "outfitDigiturt",
    // "outfitBraaains",
    // "outfitNorseCode",
    // "outfitILavaYou",
    // "outfitJuleVerny",
    // "outfitStumped",
    // "outfitStreetArt",
    // "outfitCosmicBlue",
    // "outfitColorPalette",
    // "outfitChromaticCTR",
    // "outfitTurtleSweater",
    // "outfitHowPitaful",
    // "outfitSoapPods",
    // "outfitTomatoandCheese",
    // "outfitH2Oh",
    // "outfitScarween",
    // "outfitSwords",
    // "outfitHopelessRamentic",
    // "outfitChewieCheese",
    // "outfitWoodFire",
    // "outfitHoldinHide",
    // "outfitDisasteroid",
    // "outfitRuppert",
    // "outfitBluntRazor",
    // "outfitGreenTeaRex",
    // "outfitTribeMask",
    // "outfitPhoebonachi",
    // "outfitTribeShield",
    // "outfitMultiTusking",
    // "outfitTirelessly",
    // "outfitBrontoChop",
    // "outfitTunelSun",
    // "outfitHuedini",
    // "outfitBombyman",
    // "outfitSunriseBlvd",
    // "outfitIdDie4U",
    // "outfitIntoTheGrid",
    // "outfitToontooine",
    // "outfitBitplosion",
    // "oufitItsMeCoin",
    // "outfitMaxAttack",
    // "outfitHowlODays",
    // "outfitCaptnCactus",
    // "outfitNachoHat",
    // "outfitBroncoSaurus",
    // "outfitNeckNapkin",
    // "outfitMoosli",
    // "outfitSuppaPoncho",
    // "outfitGoodFeather",
    // "outfitRanchDressing",
    // "outfitTheySeeMeRolling",
    // "outfitSirLoin",
    // "outfitAhoy",
    // "outfitLustrousPaladin",
    // "outfitVillageNinja",
    // "outfitYinYang",
    // "outfitTiki",
    // "outfitMachoLucha2",
    // "outfitCalaca",
    // "outfitMecha",
    // "outfitDiamondy",
    // "outfitEggnite",
    // "outfitSpaceSnout",
    // "outfitMugnificent",
    // "outfitDeRanged",
    "outfitKxrLogo",
    // "outfitThePro",
    // "outfitUrbanGlitch",
    // "outfitPython",
    // "outfitCyberpunk",
    // "outfitEnergyWave",
    // "outfitSolarAegis",
    // "outfitAuresis",
    // "outfitIgris",
    // "outfitVoidcore",
    // "outfitArchaicCrown",
    // "outfitBee",
    // "outfitCupcake",
    // "outfitBeru",
    // "outfitLivingGalaxy",
    // "outfitCheckmate",
    // "outfitWolf",
    // "outfitRiotPlaid",
    // "outfitBugcat",
    // "outfitGojo",
    // "outfitJinglyJester",
    // "outfitOldArt",
    // "outfitUnoReverse",
    // "outfitYinyangTakeover",
    // "outfitMahoraga",
    // "outfitToxicFire",
    // "outfitToxicChomper",
    // "outfitCrimsonHibiscus",
    // "outfitDonut",
    // "outfitPolice",
    // "outfitTopOnePercent",
    // "outfitTopTwoPercent",
    // "outfitTopThreePercent",
    // "outfitSzn2",
    // "outfitPanda",
    // "outfitDiamond",
    // "outfitAero",
    // "outfitPtero",
    // "outfitHazard",
    // "outfitMummy",
    // "outfitColdestEdge",
    // "outfitStickySituation",
    // "outfitPeru",
    // "outfitPaintSplat",
    // "outfitSacredGeometry",
    // "outfitGoldenWaffle",
    // "outfitStoneIdol",
    // "outfitMissingTexture",
    // "outfitAutumnSweater",
    // "outfitCandy",
    // "outfitVikingHelm",
    // "outfitGhost",
    // "outfitBullyGear",
    // "outfitGobble",
    // "outfitBlush",
    // "outfitPie",
    // "outfitMondrian",
    // "outfitLuna",
    // "outfitNightshadeStalker",
    // "outfitFishBowl",
    // "outfitAutumnForest",
    // "outfitPlaqueDoctor",
    // "outfitForestPlaid",
    // "outfitSpartan",
    // "outfitCatchemOl",
    // "outfitMeow",
    // "outfitPreyDinner",
    // "outfitCandyCorn",
    // "outfitVitaminD",
    // "outfitReTag",
];
const _allowedEmotes = [
    // stock
    // faces
    "emote_alienface",
    "emote_angryface",
    "emote_dabface",
    "emote_disappointface",
    "emote_greedy",
    "emote_happyface",
    "emote_headshotface",
    "emote_heartface",
    "emote_impface",
    "emote_its_ok",
    "emote_joyface",
    "emote_monocleface",
    "emote_relief",
    "emote_sadface",
    // "emote_wifail",
    // "emote_facepalm",
    // "emote_eyebags",
    // "emote_victory",
    "emote_shockface",
    "emote_shur",
    "emote_sobface",
    "emote_sunglassface",
    "emote_thinkingface",
    "emote_tongues_out",
    "emote_too_close",
    "emote_upsidedownface",
    // food
    "emote_acorn",
    "emote_bagged",
    "emote_baguette",
    "emote_cake",
    "emote_candycorn",
    "emote_chickend",
    "emote_chickendinner",
    "emote_coconut",
    "emote_cupcake",
    "emote_donut",
    "emote_eggplant",
    "emote_icecream",
    "emote_leek",
    "emote_pineapple",
    "emote_potato",
    "emote_salt",
    // animals
    "emote_cattle",
    "emote_chick",
    "emote_crab",
    "emote_dove",
    "emote_fish",
    "emote_tiny_turtle",
    "emote_turkeyanimal",
    "emote_was_a_lovely_cow",
    "emote_whale",
    // logos
    "emote_logocaduceus",
    "emote_logochrysanthemum",
    "emote_logocloud",
    "emote_logoconch",
    "emote_logocrossing",
    "emote_logoegg",
    "emote_logoeye",
    "emote_logohatchet",
    "emote_logohydra",
    "emote_logostorm",
    "emote_logosurviv",
    "emote_logoswine",
    "emote_logotwins",
    "emote_police",
    "emote_surviv",
    // words
    "emote_easy",
    "emote_gg",
    "emote_hi5",
    "emote_oof",
    "emote_pwn",
    "emote_qq",
    "emote_question",
    "emote_rawr",
    "emote_wait",
    "emote_wth",
    "emote_yeehaw",
    // other
    "emote_campfire",
    "emote_egg",
    "emote_flex",
    "emote_forest",
    "emote_heart",
    "emote_lootloot",
    "emote_new_in_town",
    "emote_pilgrimhat",
    "emote_prickly_business",
    "emote_pumpkin",
    "emote_santahat",
    "emote_send_some_potions",
    "emote_sleepy",
    "emote_snowflake",
    "emote_snowman",
    "emote_teabag",
    "emote_thumbsup",
    "emote_tombstone",
    "emote_trunk",
    "emote_you_invader",
    // flags
    "emote_flagalbania",
    "emote_flagalgeria",
    "emote_flagargentina",
    "emote_flagaustralia",
    "emote_flagaustria",
    "emote_flagazerbaijan",
    "emote_flagbelarus",
    "emote_flagbelgium",
    "emote_flagbolivia",
    "emote_flagbosnia",
    "emote_flagbrazil",
    "emote_flagcanada",
    "emote_flagchile",
    "emote_flagchina",
    "emote_flagcolombia",
    "emote_flagcroatia",
    "emote_flagczechia",
    "emote_flagdenmark",
    "emote_flagdominicanrepublic",
    "emote_flagecuador",
    "emote_flagegypt",
    "emote_flagestonia",
    "emote_flagfinland",
    "emote_flagfrance",
    "emote_flaggeorgia",
    "emote_flaggermany",
    "emote_flaggreece",
    "emote_flagguatemala",
    "emote_flaghonduras",
    "emote_flaghongkong",
    "emote_flaghungary",
    "emote_flagindia",
    "emote_flagindonesia",
    "emote_flagisrael",
    "emote_flagitaly",
    "emote_flagjapan",
    "emote_flagkazakhstan",
    "emote_flaglatvia",
    "emote_flaglibya",
    "emote_flaglithuania",
    "emote_flagmalaysia",
    "emote_flagmexico",
    "emote_flagmoldova",
    "emote_flagmorocco",
    "emote_flagnetherlands",
    "emote_flagnewzealand",
    "emote_flagnorway",
    "emote_flagpalestine",
    "emote_flagperu",
    "emote_flagphilippines",
    "emote_flagpoland",
    "emote_flagportugal",
    "emote_flagromania",
    "emote_flagrussia",
    "emote_flagserbia",
    "emote_flagsingapore",
    "emote_flagslovakia",
    "emote_flagsouthkorea",
    "emote_flagspain",
    "emote_flagsweden",
    "emote_flagswitzerland",
    "emote_flagtaiwan",
    "emote_flagthailand",
    "emote_flagtrinidad",
    "emote_flagturkey",
    "emote_flaguae",
    "emote_flaguk",
    "emote_flagukraine",
    "emote_flaguruguay",
    "emote_flagus",
    "emote_flagvenezuela",
    "emote_flagvietnam",
    "emote_flagtransgender",
    "emote_flagpride",
    "emote_flaglesbian",
    "emote_flaggay",
    "emote_flagasexual",
    "emote_flagnonbinary",
    // pass 1
    // "emote_bandagedface",
    // "emote_nooblet",
    // "emote_rainbow",
    // "emote_pooface",
    // "emote_ghost_base",
    // "emote_rip",
    // "emote_golden_bullet",
    // pass 2
    // "emote_picassoface",
    // "emote_gogo",
    // "emote_starstruck",
    // "emote_rad",
    // "emote_logometeor",
    // "emote_rainy_day",
    // "emote_buuurn",
    // pass 3
    // "emote_chimpion",
    // "emote_son",
    // "emote_stop",
    // "emote_tuff",
];

const _allowedPerks = [
    "melee_runner",
    "armor_master",
    "quick_reload",
    "melee_striker",
    "gun_master",
    "first_hit",
    "throw_slow",
    "low_hp_surge",
    "chambered",
    "mine_master",
    "leadership2",
];

export interface UnlockDef {
    readonly type: "unlock";
    name: string;
    unlocks: string[];
    free?: boolean;
}

type UnlockDefKey = "unlock_default" | "unlock_new_account" | "unlock_featured_bundles";
export const UnlockDefs: Record<UnlockDefKey, UnlockDef> = {
    unlock_default: {
        type: "unlock",
        name: "standard-issue",
        unlocks: [
            ...new Set([
                ..._allowedOutfits,
                ..._allowedMeleeSkins,
                ..._allowedEmotes,
                ..._allowedHealEffects,
                ..._allowedDeathEffects,
                ..._allowedPerks,
                ..._allowedStreaks,
                ...Object.keys(CrosshairDefs).filter(
                    (key) => key !== "crosshair_custom_image",
                ),
                // ...PassDefs.pass_survivr1.items.map((item) => item.item),
                ...allowedGuns,
                // ..._allowedGunSkins,
            ]),
        ],
    },
    unlock_new_account: {
        type: "unlock",
        name: "new-account",
        free: true,
        unlocks: ["outfitDarkShirt"],
    },
    unlock_featured_bundles: {
        type: "unlock",
        name: "featured-bundles",
        unlocks: [...new Set(_featuredBundleUnlocks)],
    },
};
